#cloud-config

runcmd:
  - rm /etc/apt/sources.list.d/ubuntu.sources

write_files:
  - path: /etc/apt/sources.list.d/ubuntu.sources
    content: |
      Types: deb
      URIs: http://archive.ubuntu.com/ubuntu
      Suites: noble noble-updates noble-backports
      Components: main universe restricted multiverse
      Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

      Types: deb
      URIs: http://security.ubuntu.com/ubuntu
      Suites: noble-security
      Components: main universe restricted multiverse
      Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
